language: php
php:
  - 7.4

before_install:
  # Install PHP CodeSniffer.
  - composer self-update;
  - composer require squizlabs/php_codesniffer:dev-master;
  - composer install;

script:
  - vendor/bin/phpcs . --standard=PSR12