language: php
php:
  - 7.4

before_install:
  # Install PHP CodeSniffer.
  - composer self-update;
  - composer require squizlabs/php_codesniffer:dev-master;
  - composer install;

script:
  - vendor/bin/phpcs --standard=PSR12 $(git diff-tree --no-commit-id --name-only -r `git log --format="%H" -n 1` | grep .php)